import Head from 'next/head';
import { MediaContextProvider } from '../media';

export const LayoutComponent = (props: any) => {
    return (
        <MediaContextProvider>
            <Head>
                <title>{props.headTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {props.header}
            {props.main}
            {props.footer}
        </MediaContextProvider>
    )
};