import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Plus from '../components/plus.component';
import Minus from '../components/minus.component';
import CountReset from '../components/countReset.component';
import { useRecoilState, useRecoilValue, useResetRecoilState } from 'recoil';
import { changeCount, count } from '../recoil/count.recoil';

const Home: NextPage = () => {

  const value = useRecoilValue(count);
  const [plusCount, setPlusCount] = useRecoilState(changeCount('+'));
  const plusFunc = () => setPlusCount(plusCount);
  const [minusCount, setMinusCount] = useRecoilState(changeCount('-'));
  const minusFunc = () => setMinusCount(minusCount);
  const resetFunc = useResetRecoilState(changeCount(''));

  return (
    <div className={styles.container}>
      <Head>
        <title>next recoil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div><Minus minusFunc={minusFunc} /><h1>{value}</h1><Plus plusFunc={plusFunc} /><br /><CountReset resetFunc={resetFunc} /></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
